version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:latest
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
      - image: circleci/redis:latest
    steps:
      - checkout
      - run:
          name: Bundler version
          command: bundle -v
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: Wait for redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Run tests
          command: bundle exec rake test
